### ISSUE TITLE
[Bug] Bulk Convert feature does not work

### ISSUE THREAD

**Issue by GPLv3-fan** [Ajatt-Tools/PasteImagesAsWebP#16]
OS: Manjaro KDE - X11
Anki: Anki 2.1.53 Beta Release Candidate 2

After clicking the button to "Bulk Convert" audios on the Browser the following error appears:

**Fehler** (error)
Es ist ein Fehler aufgetreten...

Debuginformationen:
Anki 2.1.53 (96bacf79) Python 3.9.10 Qt 6.3.0 PyQt 6.3.0
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-05-26 08:49:30
Möglicherweise beteiligte Erweiterungen: ⁨Paste Images As WebP⁩

Caught exception:
Traceback (most recent call last):
  File "/home/m/.local/share/Anki2/addons21/1151815987/bulkconvert.py", line 226, in <lambda>
    qconnect(a.triggered, lambda: on_bulk_convert(browser))
  File "/home/m/.local/share/Anki2/addons21/1151815987/bulkconvert.py", line 215, in on_bulk_convert
    dialog = BulkConvertDialog(browser)
  File "/home/m/.local/share/Anki2/addons21/1151815987/utils/gui.py", line 201, in __init__
    self._field_selector = FieldSelector()
  File "/home/m/.local/share/Anki2/addons21/1151815987/utils/gui.py", line 176, in __init__
    self._combo = CheckableComboBox()
  File "/home/m/.local/share/Anki2/addons21/1151815987/utils/checkable_combobox.py", line 25, in __init__
    palette = qApp.palette()
NameError: name 'qApp' is not defined

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/PasteImagesAsWebP/blob/main/.github/ISSUE_TEMPLATE/issue.md)
