### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fouda4ever** [Ajatt-Tools/PasteImagesAsWebP#3]
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-07-18 23:46:35

Caught exception:
Traceback (most recent call last):
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-8>", line 2, in onPaste
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\Mohammad\AppData\Roaming\Anki2\addons21\1151815987\__init__.py", line 116, in paste_event
    w.convert(mime)
  File "C:\Users\Mohammad\AppData\Roaming\Anki2\addons21\1151815987\utils\webp.py", line 167, in convert
    if self.to_webp(tmp_file, webp_filepath) is False:
  File "C:\Users\Mohammad\AppData\Roaming\Anki2\addons21\1151815987\utils\webp.py", line 141, in to_webp
    p = subprocess.Popen(stringify_args(args),
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

**Comment by tatsumoto-ren** [comment]
If you're running a 32-bit version of Windows, there's nothing that can be done.

**Comment by fouda4ever** [comment]
Thanks
